'use client';

import { useState, useEffect } from 'react';
import { User, Project } from '@/app/page';
import { Card, CardContent, CardHeader, CardTitle } from '@/src/components/ui/card';
import { Input } from '@/src/components/ui/input';
import { Button } from '@/src/components/ui/button';
import { Badge } from '@/src/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/src/components/ui/select';
import { Search, Filter, Download, ExternalLink, MapPin, User as UserIcon, DollarSign, Calendar, FileText } from 'lucide-react';
import { useBlockchain } from '@/src/hooks/useBlockchain';
import { ipfsService, ProjectData } from '@/src/lib/ipfsService';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/src/components/ui/dialog';
import jsPDF from 'jspdf';

interface TransactionHistoryProps {
  user: User;
}

export function TransactionHistory({ user }: TransactionHistoryProps) {
  const { projects } = useBlockchain();
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [projectsWithIPFS, setProjectsWithIPFS] = useState<(Project & { ipfsData?: ProjectData })[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isExportModalOpen, setIsExportModalOpen] = useState(false);
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);

  // Fetch IPFS data for projects
  useEffect(() => {
    const fetchIPFSData = async () => {
      if (projects.length > 0) {
        setIsLoading(true);
        try {
          const projectsWithIPFSData = await Promise.all(
            projects.map(async (project) => {
              if (project.ipfsHash) {
                try {
                  const ipfsData = await ipfsService.getProjectFromIPFS(project.ipfsHash);
                  return { ...project, ipfsData };
                } catch (error) {
                  console.error(`Failed to fetch IPFS data for project ${project.id}:`, error);
                  return { ...project, ipfsData: undefined };
                }
              }
              return { ...project, ipfsData: undefined };
            })
          );
          setProjectsWithIPFS(projectsWithIPFSData);
        } catch (error) {
          console.error('Error fetching IPFS data:', error);
          setProjectsWithIPFS(projects.map(p => ({ ...p, ipfsData: undefined })));
        } finally {
          setIsLoading(false);
        }
      } else {
        setProjectsWithIPFS([]);
      }
    };

    fetchIPFSData();
  }, [projects]);

  const filteredProjects = projectsWithIPFS.filter(project => {
    const matchesSearch = 
      project.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      project.description.toLowerCase().includes(searchTerm.toLowerCase()) ||
      project.location.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (project.ipfsHash && project.ipfsHash.toLowerCase().includes(searchTerm.toLowerCase())) ||
      (project.createdBy && project.createdBy.toLowerCase().includes(searchTerm.toLowerCase()));

    const matchesStatus = statusFilter === 'all' || project.status === statusFilter;

    // Role-based filtering
    const hasAccess = 
      user.role === 'public' || 
      user.role === 'government' ||
      project.contractor === user.name ||
      project.createdBy === user.name;

    return matchesSearch && matchesStatus && hasAccess;
  });

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'completed': return 'bg-green-100 text-green-800 border-green-200';
      case 'in_progress': return 'bg-blue-100 text-blue-800 border-blue-200';
      case 'approved': return 'bg-yellow-100 text-yellow-800 border-yellow-200';
      case 'planning': return 'bg-gray-100 text-gray-800 border-gray-200';
      default: return 'bg-gray-100 text-gray-800 border-gray-200';
    }
  };

  const formatDate = (timestamp: number) => {
    return new Date(timestamp).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  };

  const generatePDF = async () => {
    setIsGeneratingPDF(true);
    try {
      const pdf = new jsPDF();
      
      // Add title
      pdf.setFontSize(20);
      pdf.text('Project History Report', 20, 30);
      
      // Add generation date
      pdf.setFontSize(10);
      pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 40);
      
      // Add user info
      pdf.text(`Generated by: ${user.name} (${user.role})`, 20, 50);
      
      let yPosition = 70;
      const pageHeight = pdf.internal.pageSize.height;
      const margin = 20;
      
      filteredProjects.forEach((project, index) => {
        // Check if we need a new page
        if (yPosition > pageHeight - 60) {
          pdf.addPage();
          yPosition = 30;
        }
        
        // Project title
        pdf.setFontSize(14);
        pdf.text(`${index + 1}. ${project.ipfsData?.projectTitle || project.name}`, margin, yPosition);
        yPosition += 10;
        
        // Project details
        pdf.setFontSize(10);
        pdf.text(`Status: ${project.status.replace('_', ' ').toUpperCase()}`, margin, yPosition);
        yPosition += 6;
        
        pdf.text(`Location: ${project.ipfsData?.location || project.location}`, margin, yPosition);
        yPosition += 6;
        
        pdf.text(`Contractor: ${project.ipfsData?.localPresident || project.contractor || 'N/A'}`, margin, yPosition);
        yPosition += 6;
        
        pdf.text(`Total Budget: $${project.totalBudget.toLocaleString()}`, margin, yPosition);
        yPosition += 6;
        
        pdf.text(`Spent Funds: $${project.spentFunds.toLocaleString()}`, margin, yPosition);
        yPosition += 6;
        
        pdf.text(`Progress: ${Math.round((project.spentFunds / project.totalBudget) * 100)}%`, margin, yPosition);
        yPosition += 6;
        
        pdf.text(`Created: ${formatDate(project.createdAt)}`, margin, yPosition);
        yPosition += 6;
        
        if (project.ipfsHash) {
          pdf.text(`IPFS CID: ${project.ipfsHash}`, margin, yPosition);
          yPosition += 6;
        }
        
        if (project.createdBy) {
          pdf.text(`Signed Wallet: ${project.createdBy}`, margin, yPosition);
          yPosition += 6;
        }
        
        // Project description
        if (project.ipfsData?.projectDescription || project.description) {
          const description = project.ipfsData?.projectDescription || project.description;
          const splitDescription = pdf.splitTextToSize(`Description: ${description}`, 170);
          pdf.text(splitDescription, margin, yPosition);
          yPosition += splitDescription.length * 4;
        }
        
        yPosition += 10; // Space between projects
      });
      
      // Download the PDF
      const fileName = `project-history-${new Date().toISOString().split('T')[0]}.pdf`;
      pdf.save(fileName);
      
      setIsExportModalOpen(false);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Error generating PDF. Please try again.');
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  return (
    <Card className="bg-white shadow-sm">
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="text-xl font-bold">Project History</CardTitle>
          <div className="flex items-center space-x-2">
            <Dialog open={isExportModalOpen} onOpenChange={setIsExportModalOpen}>
              <DialogTrigger asChild>
                <Button variant="outline" size="sm" className="flex items-center space-x-2">
                  <Download className="h-4 w-4" />
                  <span>Export</span>
                </Button>
              </DialogTrigger>
              <DialogContent className="sm:max-w-md">
                <DialogHeader>
                  <DialogTitle className="flex items-center space-x-2">
                    <FileText className="h-5 w-5" />
                    <span>Export Project History</span>
                  </DialogTitle>
                </DialogHeader>
                <div className="space-y-4">
                  <p className="text-sm text-gray-600">
                    Generate a PDF report containing all project information including:
                  </p>
                  <ul className="text-sm text-gray-600 space-y-1 ml-4">
                    <li>• Project names and descriptions</li>
                    <li>• IPFS CIDs and wallet signatures</li>
                    <li>• Budget and progress information</li>
                    <li>• Location and contractor details</li>
                  </ul>
                  <div className="flex justify-end space-x-2">
                    <Button 
                      variant="outline" 
                      onClick={() => setIsExportModalOpen(false)}
                      disabled={isGeneratingPDF}
                    >
                      Cancel
                    </Button>
                    <Button 
                      onClick={generatePDF}
                      disabled={isGeneratingPDF}
                      className="flex items-center space-x-2"
                    >
                      {isGeneratingPDF ? (
                        <>
                          <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                          <span>Generating...</span>
                        </>
                      ) : (
                        <>
                          <Download className="h-4 w-4" />
                          <span>Download PDF</span>
                        </>
                      )}
                    </Button>
                  </div>
                </div>
              </DialogContent>
            </Dialog>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Filters */}
        <div className="flex flex-col sm:flex-row gap-4">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
            <Input
              placeholder="Search projects, IPFS CID, or wallet addresses..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10"
            />
          </div>
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-full sm:w-[180px]">
              <SelectValue placeholder="Filter by status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Statuses</SelectItem>
              <SelectItem value="planning">Planning</SelectItem>
              <SelectItem value="approved">Approved</SelectItem>
              <SelectItem value="in_progress">In Progress</SelectItem>
              <SelectItem value="completed">Completed</SelectItem>
            </SelectContent>
          </Select>
        </div>

        {/* Project List */}
        <div className="space-y-3">
          {isLoading ? (
            <div className="text-center py-12 text-gray-500">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto mb-4"></div>
              <p className="text-lg">Loading projects...</p>
            </div>
          ) : filteredProjects.length === 0 ? (
            <div className="text-center py-12 text-gray-500">
              <Filter className="h-12 w-12 mx-auto mb-4 text-gray-300" />
              <p className="text-lg">No projects found</p>
              <p className="text-sm">Try adjusting your search criteria</p>
            </div>
          ) : (
            filteredProjects.map((project) => (
              <Card key={project.id} className="p-4 hover:shadow-md transition-shadow border border-gray-200">
                <div className="flex items-center justify-between">
                  <div className="flex-1">
                    <div className="flex items-center space-x-3 mb-2">
                      <Badge variant="outline" className={getStatusColor(project.status)}>
                        {project.status.replace('_', ' ').toUpperCase()}
                      </Badge>
                      <span className="text-sm text-gray-500">
                        Created: {formatDate(project.createdAt)}
                      </span>
                    </div>
                    <h4 className="font-semibold text-gray-900 mb-2">
                      {project.ipfsData?.projectTitle || project.name}
                    </h4>
                    <p className="text-sm text-gray-600 mb-3">
                      {project.ipfsData?.projectDescription || project.description}
                    </p>
                    
                    {/* Project Details */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm">
                      <div className="flex items-center text-gray-600">
                        <MapPin className="h-4 w-4 mr-2 text-gray-400" />
                        <span><strong>Location:</strong> {project.ipfsData?.location || project.location}</span>
                      </div>
                      
                      <div className="flex items-center text-gray-600">
                        <UserIcon className="h-4 w-4 mr-2 text-gray-400" />
                        <span><strong>Contractor:</strong> {project.ipfsData?.localPresident || project.contractor || 'N/A'}</span>
                      </div>
                      
                      <div className="flex items-center text-gray-600">
                        <DollarSign className="h-4 w-4 mr-2 text-gray-400" />
                        <span><strong>Budget:</strong> ${project.ipfsData?.budget || project.totalBudget.toLocaleString()}</span>
                      </div>
                      
                      <div className="flex items-center text-gray-600">
                        <Calendar className="h-4 w-4 mr-2 text-gray-400" />
                        <span><strong>Start Date:</strong> {
                          project.ipfsData?.startDate 
                            ? formatDate(new Date(project.ipfsData.startDate).getTime())
                            : formatDate(project.createdAt)
                        }</span>
                      </div>
                    </div>

                    {/* IPFS and Wallet Information */}
                    <div className="mt-3 pt-3 border-t border-gray-100">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm">
                        {project.ipfsHash && (
                          <div className="flex items-center text-gray-600">
                            <ExternalLink className="h-4 w-4 mr-2 text-gray-400" />
                            <span><strong>IPFS CID:</strong> {project.ipfsHash}</span>
                            <Button
                              variant="ghost"
                              size="sm"
                              className="ml-2 h-6 px-2 text-xs"
                              onClick={() => window.open(`https://gateway.lighthouse.storage/ipfs/${project.ipfsHash}`, '_blank')}
                            >
                              View
                            </Button>
                          </div>
                        )}
                        
                        {project.createdBy && (
                          <div className="flex items-center text-gray-600">
                            <UserIcon className="h-4 w-4 mr-2 text-gray-400" />
                            <span><strong>Signed Wallet:</strong> {project.createdBy.slice(0, 6)}...{project.createdBy.slice(-4)}</span>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                  
                  <div className="text-right ml-4">
                    <p className="text-2xl font-bold text-gray-900">
                      ${project.totalBudget.toLocaleString()}
                    </p>
                    <p className="text-sm text-gray-500">
                      Total Budget
                    </p>
                    <div className="mt-2">
                      <div className="text-sm text-gray-600 mb-1">
                        Progress: {Math.round((project.spentFunds / project.totalBudget) * 100)}%
                      </div>
                      <div className="w-full bg-gray-200 rounded-full h-2">
                        <div 
                          className="bg-blue-600 h-2 rounded-full transition-all duration-300"
                          style={{ width: `${Math.min((project.spentFunds / project.totalBudget) * 100, 100)}%` }}
                        ></div>
                      </div>
                    </div>
                  </div>
                </div>
              </Card>
            ))
          )}
        </div>
      </CardContent>
    </Card>
  );
}